# Generated by Django 2.2.3 on 2020-02-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyrics_mod',
            name='lyrics_banner',
            field=models.ImageField(null=True, upload_to='lyrics_banner/'),
        ),
    ]
