# Generated by Django 2.2.3 on 2020-02-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0002_lyrics_mod_lyrics_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lyrics_admin_mod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_uname', models.CharField(max_length=50)),
                ('ad_pass', models.CharField(max_length=150)),
                ('log_type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tune',
            },
        ),
    ]
