# Generated by Django 2.2.3 on 2020-02-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0004_auto_20200205_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyrics_mod',
            name='is_live',
            field=models.BooleanField(null=True),
        ),
    ]
